import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Product from '#models/product'

export default class extends BaseSeeder {
  async run() {
    await Product.createMany([
      // VELAS
      {
        name: 'Vela Aromática Lavanda',
        description: 'Vela artesanal de cera de soja con aroma relajante de lavanda. Perfecta para crear un ambiente tranquilo y acogedor.',
        price: 24.99,
        stock: 35,
        imageUrl: 'https://images.unsplash.com/photo-1602874801007-c9aa89ed2b09',
        category: 'Velas',
        size: '12 oz',
        colors: ['Morado claro', 'Blanco'],
        scents: ['Lavanda', 'Vainilla suave'],
        shape: 'Cilíndrica',
        burnTime: 50,
        ingredients: ['Cera de soja', 'Aceite esencial de lavanda', 'Mecha de algodón'],
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'Vela Decorativa Corazón',
        description: 'Hermosa vela en forma de corazón, ideal para regalar. Hecha a mano con cera natural.',
        price: 18.99,
        stock: 28,
        imageUrl: 'https://images.unsplash.com/photo-1608181078976-e7cb6d3a940a',
        category: 'Velas',
        size: '8 oz',
        colors: ['Rosa', 'Rojo', 'Blanco'],
        scents: ['Rosas', 'Pétalos frescos'],
        shape: 'Corazón',
        burnTime: 35,
        ingredients: ['Cera de soja', 'Aceite esencial de rosa', 'Mecha de algodón'],
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'Vela Minimalista Eucalipto',
        description: 'Vela de diseño minimalista con aroma refrescante de eucalipto. Perfecto para espacios modernos.',
        price: 29.99,
        stock: 20,
        imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59',
        category: 'Velas',
        size: '16 oz',
        colors: ['Verde menta', 'Blanco crema'],
        scents: ['Eucalipto', 'Menta'],
        shape: 'Cilíndrica',
        burnTime: 60,
        ingredients: ['Cera de soja', 'Aceite esencial de eucalipto', 'Mecha de madera'],
        isActive: true,
        isFeatured: false,
      },
      {
        name: 'Vela de Té Set 12 Piezas',
        description: 'Set de 12 velas pequeñas aromáticas, perfectas para centros de mesa o ambientes íntimos.',
        price: 15.99,
        stock: 50,
        imageUrl: 'https://images.unsplash.com/photo-1598518619776-eae3f8f50b0e',
        category: 'Velas',
        size: 'Mini (12 unidades)',
        colors: ['Blanco', 'Marfil'],
        scents: ['Vainilla', 'Canela'],
        shape: 'Circular plana',
        burnTime: 4,
        ingredients: ['Cera de parafina', 'Aromas naturales'],
        isActive: true,
        isFeatured: false,
      },
      {
        name: 'Vela de Cera de Abeja Natural',
        description: 'Vela 100% cera de abeja pura, sin aditivos. Aroma natural y purificador del aire.',
        price: 34.99,
        stock: 15,
        imageUrl: 'https://images.unsplash.com/photo-1610216705781-df2fd0dc36ad',
        category: 'Velas',
        size: '10 oz',
        colors: ['Amarillo miel natural'],
        scents: ['Miel natural'],
        shape: 'Pilar',
        burnTime: 45,
        ingredients: ['Cera de abeja 100%', 'Mecha de algodón'],
        isActive: true,
        isFeatured: true,
      },

      // JABONES
      {
        name: 'Jabón Artesanal Avena y Miel',
        description: 'Jabón natural exfoliante con avena y miel. Ideal para pieles sensibles.',
        price: 8.99,
        stock: 45,
        imageUrl: 'https://images.unsplash.com/photo-1600428877861-e16f8b229619',
        category: 'Jabones',
        size: '120g',
        colors: ['Beige', 'Dorado'],
        scents: ['Miel', 'Avena'],
        shape: 'Rectangular',
        burnTime: null,
        ingredients: ['Aceite de oliva', 'Avena', 'Miel orgánica', 'Glicerina'],
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'Jabón de Lavanda Francés',
        description: 'Jabón aromático con lavanda de Provenza. Propiedades calmantes y relajantes.',
        price: 10.99,
        stock: 38,
        imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108',
        category: 'Jabones',
        size: '150g',
        colors: ['Morado', 'Lila'],
        scents: ['Lavanda francesa'],
        shape: 'Ovalada',
        burnTime: null,
        ingredients: ['Aceite de coco', 'Manteca de karité', 'Aceite esencial de lavanda'],
        isActive: true,
        isFeatured: false,
      },
      {
        name: 'Jabón Exfoliante de Café',
        description: 'Jabón energizante con café molido. Exfoliación suave y aroma estimulante.',
        price: 9.99,
        stock: 32,
        imageUrl: 'https://images.unsplash.com/photo-1600428877861-e16f8b229619',
        category: 'Jabones',
        size: '130g',
        colors: ['Café', 'Marrón'],
        scents: ['Café', 'Chocolate'],
        shape: 'Cuadrada',
        burnTime: null,
        ingredients: ['Café orgánico', 'Aceite de oliva', 'Manteca de cacao'],
        isActive: true,
        isFeatured: true,
      },

      // WAX MELTS
      {
        name: 'Wax Melts Canela y Naranja',
        description: 'Set de ceras aromáticas para derretir. Aroma cálido y especiado.',
        price: 12.99,
        stock: 40,
        imageUrl: 'https://images.unsplash.com/photo-1608181078976-e7cb6d3a940a',
        category: 'Wax & Más',
        size: '6 cubos',
        colors: ['Naranja', 'Canela'],
        scents: ['Canela', 'Naranja dulce', 'Clavo'],
        shape: 'Cubos',
        burnTime: 8,
        ingredients: ['Cera de soja', 'Aceites esenciales'],
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'Difusor de Varillas Bambú',
        description: 'Difusor con varillas de bambú y aroma de bosque fresco. Larga duración.',
        price: 22.99,
        stock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1602874801007-c9aa89ed2b09',
        category: 'Wax & Más',
        size: '200ml',
        colors: ['Transparente'],
        scents: ['Bambú', 'Té verde', 'Bergamota'],
        shape: 'Botella',
        burnTime: null,
        ingredients: ['Aceite base', 'Aceites esenciales', 'Varillas de bambú'],
        isActive: true,
        isFeatured: false,
      },
    ])
  }
}
